name: deploy

on: 
  pull_requests:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
    - uses: actions/checkout@v2
    - run: mkdir -p /home/runner/.npm
      continue-on-error: true

    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: 12
        cache: 'npm'
        cache-dependency-path: ./package-lock.json
  
    
    - name: npm install
      run: npm install
    - name: npm install serverless
      run: npm i -g serverless serverless-tencent
    - name: run eslint fix
      run: eslint "./**.js" --fix

